{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:pip-installer:pip:1.0:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:pip-installer:pip:1.0.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:pip-installer:pip:1.0.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:pip-installer:pip:1.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:pip-installer:pip:1.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:pip-installer:pip:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "1.2.1",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2013-1629"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "pip",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "1.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.0.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.0.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.2"
                      },
                      {
                        "version_affected": "\u003c=",
                        "version_value": "1.2.1"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "pip-installer"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "pip before 1.3 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to a \"pip install\" operation."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "http://www.pip-installer.org/en/latest/installing.html",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "http://www.pip-installer.org/en/latest/installing.html"
        },
        {
          "name": "http://www.pip-installer.org/en/latest/news.html#changelog",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "http://www.pip-installer.org/en/latest/news.html#changelog"
        },
        {
          "name": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/",
          "refsource": "MISC",
          "tags": [],
          "url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/"
        },
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=968059",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=968059"
        },
        {
          "name": "https://github.com/pypa/pip/issues/425",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://github.com/pypa/pip/issues/425"
        },
        {
          "name": "https://github.com/pypa/pip/pull/791/files",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://github.com/pypa/pip/pull/791/files"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "MEDIUM",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 6.8,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 8.6,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": true
    }
  },
  "lastModifiedDate": "2013-09-24T14:32Z",
  "publishedDate": "2013-08-06T02:52Z"
}