{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.40:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.41:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.42:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.43:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.44:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.45:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.46:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.47:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.48:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:0.6.49:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:python:setuptools:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "0.7b4",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2013-1633"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "setuptools",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "0.6.40"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.41"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.42"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.43"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.44"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.45"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.46"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.47"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.48"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "0.6.49"
                      },
                      {
                        "version_affected": "\u003c=",
                        "version_value": "0.7b4"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "python"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "easy_install in setuptools before 0.7 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to the default use of the product."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/",
          "refsource": "MISC",
          "tags": [],
          "url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/"
        },
        {
          "name": "https://pypi.python.org/pypi/setuptools/0.9.8#changes",
          "refsource": "CONFIRM",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://pypi.python.org/pypi/setuptools/0.9.8#changes"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "MEDIUM",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 6.8,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 8.6,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": true
    }
  },
  "lastModifiedDate": "2013-10-11T13:59Z",
  "publishedDate": "2013-08-06T02:52Z"
}