{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:pydio:cells:*:*:*:*:*:*:*:*",
            "versionEndExcluding": "1.5.0",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2019-12902"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "cells",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "0.9.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.0.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.0.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.0.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.0.3"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.0.4"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.2.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.2.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.2.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.2.3"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.2.4"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.2.5"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.4.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.4.1"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "pydio"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Pydio Cells before 1.5.0 does incomplete cleanup of a user's data upon deletion. This allows a new user, holding the same User ID as a deleted user, to restore the deleted user's data."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-200"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://pydio.com/en/community/releases/pydio-cells/pydio-cells-150-performances-features-security",
          "refsource": "MISC",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://pydio.com/en/community/releases/pydio-cells/pydio-cells-150-performances-features-security"
        },
        {
          "name": "https://research.loginsoft.com/vulnerability/multiple-vulnerabilities-in-pydio-cells-1-4-1/",
          "refsource": "MISC",
          "tags": [
            "Release Notes",
            "Third Party Advisory"
          ],
          "url": "https://research.loginsoft.com/vulnerability/multiple-vulnerabilities-in-pydio-cells-1-4-1/"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "SINGLE",
        "availabilityImpact": "NONE",
        "baseScore": 4,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "vectorString": "AV:N/AC:L/Au:S/C:P/I:N/A:N",
        "version": "2.0"
      },
      "exploitabilityScore": 8,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    },
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 6.5,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "privilegesRequired": "LOW",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "version": "3.0"
      },
      "exploitabilityScore": 2.8,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2019-06-24T01:19Z",
  "publishedDate": "2019-06-20T00:15Z"
}